apiVersion: v1
kind: ConfigMap
metadata:
  name: logiflow-config
  namespace: logiflow
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_RABBITMQ_HOST: "rabbitmq-service"
  SPRING_RABBITMQ_PORT: "5672"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  PEDIDO_SERVICE_URL: "http://pedido-service:8082"
  FLEET_SERVICE_URL: "http://fleet-service:8083"
  BILLING_SERVICE_URL: "http://billing-service:8084"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8086"
  TRACKING_SERVICE_URL: "http://tracking-service:8087"
  GRAPHQL_SERVICE_URL: "http://graphql-service:8088"
  WEBSOCKET_SERVICE_URL: "http://websocket-service:8089"
---
apiVersion: v1
kind: Secret
metadata:
  name: logiflow-secrets
  namespace: logiflow
type: Opaque
stringData:
  SPRING_RABBITMQ_USERNAME: "admin"
  SPRING_RABBITMQ_PASSWORD: "admin123"
  JWT_SECRET: "logiflow-jwt-secret-key-2026"
